name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - pip:
    # Snowpark
    - snowflake-snowpark-python[pandas]==1.3.0 #0.10.0
    # Basics
    - pandas==1.5.3 #1.4.3
    - numpy==1.23.5 #1.22.3
    # ML
    - scikit-learn==1.2.2 #1.1.1
    - lightgbm==3.3.5 #3.2.1
    - xgboost==1.7.3 #1.5.0
    # Visualization
    - scipy==1.10.1 #1.7.1
    - seaborn==0.12.2 #0.11.2
    - matplotlib==3.7.1
    # Misc
    - cloudpickle==2.0.0
    - jupyter==1.0.0
    - cachetools==4.2.2
    - joblib==1.1.1
    - imbalanced-learn==0.10.1
    - sqlalchemy==1.4.39
    - colorlog==5.0.1
    - optuna
